### ISSUE TITLE
Agree on database design (schema)

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/tech-access#12]
Also create markdown file with overview of db schema.

25-60 minutes

*If time*, please include ideas for db tables for our user stretch goal.

**Comment by VirtualDOMinic** [comment]
Shared doc to aid discussions @sunuwars @sbinlondon @MissArray 
https://hackmd.io/9qm5zyXMSpemEm076LmRfA

**Comment by MissArray** [comment]
* Re: online courses, perhaps it's more important to display details on the course provider?
* Reconsider 'country' and 'city' columns: how useful are they for online courses? Might we want to merge them into 'country/city', separating values with e.g. comma where both are supplied, and rename the 'city' column into something like 'provider'?
* Consider 'edge cases', such as personal accounts and forum threads (one example included: 'Front-end web developer career for person with a disability?')
