### ISSUE TITLE
Create JS functions to manage DB query results

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/tech-access#28]
Relates to #25 

This will likely be revisited (not quite "ongoing", but not done all at once) as the database queries change.

**Comment by VirtualDOMinic** [comment]
About to have a go at using a few object/array methods to get the results we want in this repl.it:

https://repl.it/@VirtualDOMinic/PeruLargeTelevisions

**Comment by VirtualDOMinic** [comment]
@sunuwars has created a function (and an example handlebars template) to do this on branch "query-and-data-structure". Me and @MissArray to continue this by checking what advice Aisha has, etc.

**Comment by sbinlondon** [comment]
Somewhat sorted! 🎉
