### ISSUE TITLE
rephrase google doc questionaire question

### ISSUE THREAD

**Issue by sunuwars** [fac-14/tech-access#4]
Q. Contact details of a person in tech *with a similar background/identity to yourself*, to ask questions and receive mentoring from	
and 
Q. Contact details of a person in tech *with a different background/identity to yourself*, to ask questions and receive mentoring from	
Can these two be rephrased as:
Q. How important is it for you to have a peer/mentor for your learning
Q. I prefer my peer/mentor to be of (my own background/any background) please tick one.

**Comment by VirtualDOMinic** [comment]
> relates #3

**Comment by VirtualDOMinic** [comment]
Updated to:
- Contact details of a peer/mentor who works in tech
- How important is it for this peer/mentor to have a similar identity/background to you?

**Comment by sunuwars** [comment]
👍
