### ISSUE TITLE
Agree updated interview Qs and conduct interviews

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/tech-access#49]
* Agree updated interview questions (see comments on this issue)

* Conduct interviews! Kate and Dom to do so in Space4. Sangita and Art to do so at the job centre.

Shortened URL: http://bit.do/tech-access

**Comment by VirtualDOMinic** [comment]
URL they can navigate to: http://bit.do/tech-access

* Did you find the app intuitive to use?
* Anything confusing/ambiguous?
* What did you think of the way your results were presented to you?
* Any comments on the general look/feel/design of the app? Happy with the colour scheme?
* Can you think of any features that would make this app more useful to you?

**Comment by sunuwars** [comment]
do you find this app useful/ would you use this app?

**Comment by MissArray** [comment]
Yep, I drafted similarly phrased questions:

* How easy was it to navigate through the app?
* Was it clear what each category/checkbox referred to?
* Was it easy to read the text?
* If you got results that you thought were useful to you, what would you like to do with them? (E.g. save them as a PDF file)
